# Markdown syntext
*Italic*
**Bold**
*** Bold Italic ***
<s> Strikethrough </s>
# Header
## Smaller header
###### You can go six levels down on Headers ######

Carriage return is line break


Two carriage returns is new para


* an asterisk starts an unordered list
* and this is another item in the list
+ or you can also use the + character to indent more
- or the - character to indent less

To start an ordered list, write this:

1. this starts a list *with* numbers
+  this will show as number "2"
*  this will show as number "3."
9. any number, +, -, or * will keep the list going.
    * just indent by 4 spaces (or tab) to make a sub-list
        1. keep indenting for more sub lists
    * here i'm back to the second level

> Use it if you're quoting a person, a song or whatever.

> You can use *italic* or lists inside them also.
And just like with other paragraphs,
all of these lines are still
part of the blockquote, even without the > character in front.

To end the blockquote, just put a blank line before the following
paragraph.

### More really useful markdown tricks here
https://sourceforge.net/p/jupiter/wiki/markdown_syntax/

### Important Jupyter commands
* Interrupt long running programs : Menu Kernel->Interrupt. Or simply press stop button
* Clear cell output : Menu cell-> current outputs -> clear

# Now Lets Start with Python 

### We use Python 2.7

### Strings and formatting strings

* Strings in Python are lists of characters
* Python strings are immutable

In [137]:
s = 'Hello, world.'
str(s)
repr(s)
str(1.0/7.0)
repr(1.0/7.0)

x = 10 * 3.25
y = 200 * 200
s = 'The value of x is ' + repr(x) + ', and y is ' + repr(y) + '...'
print s

print '{1} and {0}'.format('spam', 'eggs')


print 'The story of {0}, {1}, and {other}.'.format('Bill', 'Manfred',other='Georg')

print bin(1000)
print hex(1000)
print round(3.1432321,2)

s1  = 'this is all lowercase sentence'
print s1.islower()
print s1.isupper()
print s1.count('e')


The value of x is 32.5, and y is 40000...
eggs and spam
The story of Bill, Manfred, and Georg.
0b1111101000
0x3e8
3.14
True
False
5


In [141]:
s = 'hello world'

print s.split('e')
print s.partition('e')

print s.upper()
print s.lower()
print s.capitalize()

print s.count('o')
print s.find('o')

print s.center(20,' ')

print s.isalnum()
s1 = "hello"
print s1.isalnum()

print '{:06.2f}'.format(3.141592653589793)

print '{:04d}'.format(42)

print '{first} {last}'.format(first='Hodor', last='Hodor!')

from datetime import datetime
print '{:%Y-%m-%d %H:%M}'.format(datetime(2001, 2, 3, 4, 5))

['h', 'llo world']
('h', 'e', 'llo world')
HELLO WORLD
hello world
Hello world
2
4
    hello world     
False
True
003.14
0042
Hodor Hodor!
2001-02-03 04:05


For more formatting options : https://pyformat.info/

### for x in range(1,11):
...     print '{0:2d} {1:3d} {2:4d}'.format(x, x*x, x*x*x)

'12'.zfill(5)

print 'We are the {} who say "{}!"'.format('knights', 'Ni')


import math
print 'The value of PI is approximately {0:.3f}.'.format(math.pi)

table = {'Sjoerd': 4127, 'Jack': 4098, 'Dcab': 8637678}
print ('Jack: {0[Jack]:d}; Sjoerd: {0[Sjoerd]:d}; '
...        'Dcab: {0[Dcab]:d}'.format(table))


import math
print 'The value of PI is approximately %5.3f.' % math.pi

#### Really cool string trick. Note How ",".join is used useful for creating csv files

In [154]:
print ",".join(["f1","f2","f3"])
print ",".join(str(n) for n in range(10))

f1,f2,f3
0,1,2,3,4,5,6,7,8,9


### File Operations

In [24]:
f = open('testwritefile', 'w')
print f

f.write('This is a test\n')

# Convert everything to String before writing
value = ('the answer', 42)
s = str(value)
f.write(s)

f.close()

f = open('testwritefile', 'r')
for line in f:
        print line,
f.close()

f = open('testwritefile', 'r+')
f.write('This is another test\n')
f.close()

f = open('testwritefile', 'r')
for line in f:
        print line,
f.close()


        

<open file 'testwritefile', mode 'w' at 0x1057096f0>
This is a test
('the answer', 42) This is another test
answer', 42) This is another test
answer', 42)


In [103]:
# Difeferent reads
f = open('testwritefile', 'r')
s = f.read() #entire file or f.read(n) n bytes
print s
f.close()



This is another test
answer', 42)


In [32]:
f = open('testwritefile', 'r')
s = f.readline()
print s

This is another test



In [5]:
# json file. Also note pretty print 

""""""
# Put following in data.json
{
 "maps":[
         {"id":"blabla","iscategorical":"0"},
         {"id":"blabla","iscategorical":"0"}
        ],
"masks":
         {"id":"valore"},
"om_points":"value",
"parameters":
         {"id":"valore"}
}
""""""
import json
from pprint import pprint

with open('/Users/kavap/Documents/learn/python/data/data.json') as data_file:    
    data = json.load(data_file)
pprint(data)

{u'maps': [{u'id': u'blabla', u'iscategorical': u'0'},
           {u'id': u'blabla', u'iscategorical': u'0'}],
 u'masks': {u'id': u'valore'},
 u'om_points': u'value',
 u'parameters': {u'id': u'valore'}}


### Get Data from URL

In [7]:
import csv
import urllib2

url = 'http://winterolympicsmedals.com/medals.csv'
response = urllib2.urlopen(url)
cr = csv.reader(response)

for row in cr:
    print row
    
# for single JSON record coming back
import json

url = "http://validate.jsontest.com/?json=%7B%22key%22:%22value%22%7D"
response = urllib2.urlopen(url)
data = json.load(response)
print data



{u'validate': True, u'object_or_array': u'object', u'parse_time_nanoseconds': 20644, u'empty': False, u'size': 1}


## Data Structures :

* To get size of any data structure referenced by variable b, use : sys.getsizeof(v)


### Lists
* A List if ordered sequence of items 
* Lists store references to the objects in them
    * So if a List is copied or assigned to new list variable, the new list receives references to the objects in original list and not copies of original list
    * Also l1.extend(l2) will extend l1 by references of all element references pointed to by l2
    * Another example : l = [0]*8 will create l with 8 references to same integer object 0
        * But when you subsequently say l[2] = 5, reference at 2 will point to new integer object 2
    * Python preallocates space to lists and dynamically double the size of allocated space as the List grows.
        * Python uses a algorith called "Amortization" to preallocate the space. Pre allocating space may seem inefficient at first (since adding space for new element in real time may have O(n) time complexity
            * Amortized cost of Array(/List) of size n (n is large) is ~ O(1)
* A Set is collection of unique items
* Differences between Set and List
    * Set : Unique, Not ordered, No indexed access, All elements of same type
    * List : Non unique, ordered, Indexed access, elements can have diff types


In [14]:
list_1 = ['a','c','a','b','a','d','c','b','d']

In [98]:
print list_1

['a', 'c', 'a', 'b', 'a', 'd', 'c', 'b', 'd']


In [99]:
list_1.sort()

In [100]:
print list_1

['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd']


In [15]:
list_2 = ['1','2']

In [16]:
list_1.append(list_2)

In [17]:
print list_1

['a', 'c', 'a', 'b', 'a', 'd', 'c', 'b', 'd', ['1', '2']]


In [18]:
list_1.extend(list_2)

In [19]:
print list_1

['a', 'c', 'a', 'b', 'a', 'd', 'c', 'b', 'd', ['1', '2'], '1', '2']


In [21]:
# Wrong syntext
print list_1[9,1]

TypeError: list indices must be integers, not tuple

In [20]:
# Correct Syntext
print list_1[9][1]

2


In [22]:
print list_1.index('b')

3


In [23]:
# Value error when element not found
print list_1.index('z')

ValueError: 'z' is not in list

In [24]:
# pop() and remove()
list_1 = ['a','c','a','b','a','d','c','b','d']

list_1.insert(4,'inserted')
list_1.insert(4,'inserted')
list_1.insert(4,'inserted')
list_1.insert(4,'inserted')

print list_1

print list_1.pop()
print list_1

print list_1.pop(0)
print list_1

print list_1.pop(3)
print list_1

print list_1.remove('inserted')
print list_1
print list_1.remove('inserted')
print list_1
print list_1.remove('inserted')
print list_1
# This will produce value error. Can catch in try execpt and have removal in loop
print list_1.remove('inserted')
print list_1



['a', 'c', 'a', 'b', 'inserted', 'inserted', 'inserted', 'inserted', 'a', 'd', 'c', 'b', 'd']
d
['a', 'c', 'a', 'b', 'inserted', 'inserted', 'inserted', 'inserted', 'a', 'd', 'c', 'b']
a
['c', 'a', 'b', 'inserted', 'inserted', 'inserted', 'inserted', 'a', 'd', 'c', 'b']
inserted
['c', 'a', 'b', 'inserted', 'inserted', 'inserted', 'a', 'd', 'c', 'b']
None
['c', 'a', 'b', 'inserted', 'inserted', 'a', 'd', 'c', 'b']
None
['c', 'a', 'b', 'inserted', 'a', 'd', 'c', 'b']
None
['c', 'a', 'b', 'a', 'd', 'c', 'b']


ValueError: list.remove(x): x not in list

In [25]:
# sort() ...and its options
list_1 = ['a','c','a','b','a','d','c','b','d']

list_1.insert(4,'inserted')
list_1.insert(4,'inserted')
list_1.insert(4,'inserted')
list_1.insert(4,'inserted')

list_1.reverse()
print list_1

list_1.sort()
print list_1

list_1.sort(reverse=True)
print list_1

list_2 = [('k1','v1'),('k3','v3'),('k2','v2')]

list_2.sort(key= lambda x:x[0],reverse=True)
print list_2


['d', 'b', 'c', 'd', 'a', 'inserted', 'inserted', 'inserted', 'inserted', 'b', 'a', 'c', 'a']
['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd', 'inserted', 'inserted', 'inserted', 'inserted']
['inserted', 'inserted', 'inserted', 'inserted', 'd', 'd', 'c', 'c', 'b', 'b', 'a', 'a', 'a']
[('k3', 'v3'), ('k2', 'v2'), ('k1', 'v1')]


In [26]:
# Count number of elements that equal to x
list_1.count('a')

3

In [91]:
l1 = [1,2]
l2 = [3,4]
l3 = [5,6]

print l1
print l2

l1.append(l2)
print l1

l2.extend(l3)
print l2

[1, 2]
[3, 4]
[1, 2, [3, 4]]
[3, 4, 5, 6]


#### List slicing
Think of List slicing as ability to sequentially navigate the list in different ways :
* Walk the list forward, reverse, stepwise
* Start the walk from any index that can be specified as offset from head or tail
* Specify points to start and stop the walk


In [44]:


l1 = [1,2,3,4,5,6,7,8,9,10]

print l1[0:3]
print l1[0:6:2]
print l1[2:4]
print l1[2:]
print l1[:4] # begining to index 4
print l1[-1] # last item
print l1[-2:] # last two items
print l1[:-2] # everything except last two items
l2 = l1[:] # make a copy of whole array
print l2

# note :: instead of :
print l1[::-1]  # access list in reverse 
print l1[::-2]  # access list in reverse in steps of 2
print l1[3::-1] # start from index 3 and reverse list
print l1[8::-2] # start from index 8 and reverse list in steps of 2



[1, 2, 3]
[1, 3, 5]
[3, 4]
[3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4]
10
[9, 10]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[10, 8, 6, 4, 2]
[4, 3, 2, 1]
[9, 7, 5, 3, 1]


### Dictionaries

In [54]:
my_dict = {'k1':1,'k2':'test','k3':True}

In [16]:
print my_dict

{'k3': True, 'k2': 'test', 'k1': 1}


In [18]:
print my_dict['k3']

True


In [20]:
print my_dict['k2'][1].upper()

E


In [21]:
d = {}
d['k1'] = 'val1'
d['k2'] = 'val2'
print d

{'k2': 'val2', 'k1': 'val1'}


In [55]:
for item in my_dict.iteritems():
    print item

('k3', True)
('k2', 'test')
('k1', 1)


In [56]:
for item in my_dict.iterkeys():
    print item

k3
k2
k1


In [57]:
for item in my_dict.itervalues():
    print item

True
test
1


In [62]:
my_dict.viewitems()
my_dict.viewkeys()
my_dict.viewvalues()


dict_values([True, 'test', 1])

In [63]:
list(my_dict.viewitems())

[('k3', True), ('k2', 'test'), ('k1', 1)]

In [64]:
list(my_dict.viewvalues())

[True, 'test', 1]

In [22]:
d['k3'] = d

In [23]:
print d

{'k3': {...}, 'k2': 'val2', 'k1': 'val1'}


In [ ]:
### sys module : Acceessing commandline parameters, etc

In [56]:
import sys

print sys.argv
print sys.argv[0] # name of this python script
print sys.argv[1] # first parameter
print sys.argv[2]
print sys.path
print sys.platform
print sys.__stdin__
print sys.__stdout__
print sys.__stderr__
print sys.version

['/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py', '-f', '/Users/kavap/Library/Jupyter/runtime/kernel-151d98b8-a04b-4548-94ca-a9113589e109.json']
/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py
-f
/Users/kavap/Library/Jupyter/runtime/kernel-151d98b8-a04b-4548-94ca-a9113589e109.json
['', '/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python27.zip', '/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7', '/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/plat-darwin', '/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/plat-mac', '/Applications/Canopy.app/appdata/canopy-1.7.4.3348.macosx-x86_64/Canopy.app/Contents/lib/python2.7/plat-mac/lib-scriptpackages', '/Applications/Canopy.app/appdata/canopy-1.7.4.

### Passing arguments

In [65]:

import sys
arguments = sys.argv

print arguments
print arguments[1:]

['/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py', '-f', '/Users/kavap/Library/Jupyter/runtime/kernel-151d98b8-a04b-4548-94ca-a9113589e109.json']
['-f', '/Users/kavap/Library/Jupyter/runtime/kernel-151d98b8-a04b-4548-94ca-a9113589e109.json']


### Access OS commands

https://docs.python.org/2/library/os.html

In [64]:
# Remember: os.system() doesnt return output of command ..just the exit status
import os
output = os.system("ls")
print output # Returns exit status of OS command


0


In [47]:
# This one is specific to Jupyter notebook
!ls

Decorators.ipynb
Python - Summary of Python Statements and Jupyter formatting.ipynb
Python-for-Algorithms--Data-Structures--and-Interviews-master.zip
Statistics-Notes-master.zip
Udemy---Machine-Learning-master.zip
Udemy-notes-master.zip
Untitled.ipynb
Untitled1.ipynb
Untitled2.ipynb
code notebooks from python course
spark-notebook-examples-master
spark-notebook-examples-master.zip
test.ipynb
testfile.txt
testwritefile


In [27]:
file = open("1800.csv")

In [29]:
file.readlines()

[]

#### Remember : range or xrange doesn't return uppper bound of range. So following returns till 6. By default the range starts from 0

In [67]:
for n in xrange(7):
    print n

0
1
2
3
4
5
6


In [104]:
x = 9
if x>=25:
    print "yes"
elif x< 10:
    print "maybe"
else:
    print "middle"
    
    

maybe


In [39]:
l = [1,2,3,4,5,7,8,2,12,13,17,55,66,43,42]
l_even = []
for element in l:
    if element%2 == 0:
        l_even.append(element)
print l_even
print set(l_even)
set_even = set()
for element in l_even:
    set_even.add(element)
print set_even

[2, 4, 8, 2, 12, 66, 42]
set([2, 4, 8, 42, 12, 66])
set([2, 4, 8, 42, 12, 66])


In [40]:
sum = 0
for element in l:
    sum +=element
print sum

280


In [41]:
for item in "Praful K":
    print item

P
r
a
f
u
l
 
K


In [42]:
string_set = set("praful kava")
string_set

{' ', 'a', 'f', 'k', 'l', 'p', 'r', 'u', 'v'}

In [49]:
unique_char_l = []
for item in string_set:
    unique_char_l.append(item)
print unique_char_l 
unique_char_l.sort()
unique_char_l
    

['a', ' ', 'f', 'k', 'l', 'p', 'r', 'u', 'v']


[' ', 'a', 'f', 'k', 'l', 'p', 'r', 'u', 'v']

In [51]:
!date

Sat Jan 21 13:41:12 EST 2017


In [52]:
tuple_list = [(1,2),(3,4),(5,6)]
tuple_list

[(1, 2), (3, 4), (5, 6)]

In [55]:
for (a,b) in tuple_list:
    print a,b

1 2
3 4
5 6


In [56]:
d = {'k1':'v1','k2':'v2'}
for k,v in d.iteritems():
    print k,v
    

k2 v2
k1 v1


In [34]:
x = range(1,10)
x

x = range(1,21,3)
x

x = xrange(10)
x # shows just range(10) string as xrange is dynamic iterator 
for n in x:
    print n

0
1
2
3
4
5
6
7
8
9


In [64]:
for y in x:
    ## print y
    if y == 2:
        continue
    elif y < 5:
        print 'less than 5'
    elif y == 5:
        print 'reached 5'
        break

less than 5
less than 5
less than 5
reached 5


[1, 4, 7, 10, 13, 16, 19]

In [68]:
for y in x:
    if y > 10:
        print y
    else:
        print y+1

2
5
8
11
13
16
19


test

In [69]:
st = " print only words that start with s in this sentence"

In [85]:
for word in st.split(' '):
    if word.startswith('s'):
        print word

start
s
sentence


In [88]:
for word in st.split(' '):
    if len(word)%2 ==0 :
        print word


only
that
with
in
this
sentence


In [89]:
[word[0] for word in st.split()]

['p', 'o', 'w', 't', 's', 'w', 's', 'i', 't', 's']

In [82]:
for a in range(0,11,2):
    print a

0
2
4
6
8
10


In [84]:
l = [number for number in range(51) if number%2 ==0]
l

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50]

In [90]:
""""""
This is Doc String for function
""""""

SyntaxError: invalid syntax (<ipython-input-90-ca10cde97e30>, line 2)

In [91]:
globals()
locals()

{'In': ['',
  u"list_1 = ['a','c','a','b','a','d','c','b','d']",
  u'print list_1',
  u'list_1.sort()',
  u'print list_1',
  u"list_2 = ['1','2']",
  u'list_3 = list_1.append(list_2)',
  u'print list_3',
  u'list_1.append(list_2)',
  u'print list_1',
  u'print list_1[1,1]',
  u'print list_1[9,1]',
  u'print list_1[9][0]',
  u'print list_1[9][1]',
  u"my_dict = {'k1':1,'k2':'test','k3':true}",
  u"my_dict = {'k1':1,'k2':'test','k3':True}",
  u'print my_dict',
  u"print my_dict['k1']",
  u"print my_dict['k3']",
  u"print my_dict['k2'].upper()",
  u"print my_dict['k2'][1].upper()",
  u"d = {}\nd['k1'] = 'val1'\nd['k2'] = 'val2'\nprint d",
  u"d['k3'] = d",
  u'print d',
  u"get_ipython().system(u'ls')",
  u"get_ipython().system(u'env')",
  u"get_ipython().system(u'ls')",
  u'file = open("1800.csv")',
  u'file.read()',
  u'file.readlines()',
  u'x = 25\nif x>25:\n    print "yes"\nelseif x< 10:\n    print "maybe"\nelse:\n    print "middle"\n    \n    ',
  u'x = 25\nif x>25:\n    print "yes"

In [96]:
str = "Hello Mr Praful It's a fine Sunday"
upperCount = 0
lowerCount = 0
for a in str:
    if a == a.lower():
        lowerCount+=1
    else:
        upperCount+=1
print "The String has %d Uppercase and %d Lowercase letters" %(upperCount,lowerCount)

The String has 5 Uppercase and 29 Lowercase letters


In [97]:
l = [1,2,3,2,3,4,1,4,5,2,1]

def uniqList(l):
    return list(set(l))

print uniqList(l)

[1, 2, 3, 4, 5]


In [103]:
fl = open("Book.txt")

words = []

for line in fl:
    lineWords = line.split(' ')
    for word in lineWords:
        words.append(word)

words

['Self-Employment:',
 'Building',
 'an',
 'Internet',
 'Business',
 'of',
 'One\r\n',
 'Achieving',
 'Financial',
 'and',
 'Personal',
 'Freedom',
 'through',
 'a',
 'Lifestyle',
 'Technology',
 'Business\r\n',
 'By',
 'Frank',
 'Kane\r\n',
 '\r\n',
 '\r\n',
 '\r\n',
 'Copyright',
 '\xa9',
 '2015',
 'Frank',
 'Kane.',
 '\r\n',
 'All',
 'rights',
 'reserved',
 'worldwide.\r\n',
 '\r\n',
 '\r\n',
 'CONTENTS\r\n',
 'Disclaimer\r\n',
 'Preface\r\n',
 'Part',
 'I:',
 'Making',
 'the',
 'Big',
 'Decision\r\n',
 'Overcoming',
 'Inertia\r\n',
 'Fear',
 'of',
 'Failure\r\n',
 'Career',
 'Indoctrination\r\n',
 'The',
 'Carrot',
 'on',
 'a',
 'Stick\r\n',
 'Ego',
 'Protection\r\n',
 'Your',
 'Employer',
 'as',
 'a',
 'Security',
 'Blanket\r\n',
 'Why',
 'it\x92s',
 'Worth',
 'it\r\n',
 'Unlimited',
 'Growth',
 'Potential\r\n',
 'Investing',
 'in',
 'Yourself,',
 'Not',
 'Someone',
 'Else\r\n',
 'No',
 'Dependencies\r\n',
 'No',
 'Commute\r\n',
 'Freedom',
 'to',
 'Live',
 'Where',
 'You',
 'Want\

In [109]:
import re

f1 = open("Book.txt")

for line in f1:
    splitExpr = "\b[^\s\r\n]+\b"
    lineWords = re.split(splitExpr,line)
    for word in lineWords:
        words.append(word)

words    
    

['Self-Employment:',
 'Building',
 'an',
 'Internet',
 'Business',
 'of',
 'One\r\n',
 'Achieving',
 'Financial',
 'and',
 'Personal',
 'Freedom',
 'through',
 'a',
 'Lifestyle',
 'Technology',
 'Business\r\n',
 'By',
 'Frank',
 'Kane\r\n',
 '\r\n',
 '\r\n',
 '\r\n',
 'Copyright',
 '\xa9',
 '2015',
 'Frank',
 'Kane.',
 '\r\n',
 'All',
 'rights',
 'reserved',
 'worldwide.\r\n',
 '\r\n',
 '\r\n',
 'CONTENTS\r\n',
 'Disclaimer\r\n',
 'Preface\r\n',
 'Part',
 'I:',
 'Making',
 'the',
 'Big',
 'Decision\r\n',
 'Overcoming',
 'Inertia\r\n',
 'Fear',
 'of',
 'Failure\r\n',
 'Career',
 'Indoctrination\r\n',
 'The',
 'Carrot',
 'on',
 'a',
 'Stick\r\n',
 'Ego',
 'Protection\r\n',
 'Your',
 'Employer',
 'as',
 'a',
 'Security',
 'Blanket\r\n',
 'Why',
 'it\x92s',
 'Worth',
 'it\r\n',
 'Unlimited',
 'Growth',
 'Potential\r\n',
 'Investing',
 'in',
 'Yourself,',
 'Not',
 'Someone',
 'Else\r\n',
 'No',
 'Dependencies\r\n',
 'No',
 'Commute\r\n',
 'Freedom',
 'to',
 'Live',
 'Where',
 'You',
 'Want\

In [35]:
str1 = "helleh"
str2 = "Praful"

def isPelindrome(str):
    strRev = str[::-1]
    print strRev
    if strRev == str:
        return True
    else:
        return False

print isPelindrome(str1)
print isPelindrome(str2)

helleh
True
lufarP
False


In [46]:
str1 = "helleh"
str2 = "Praful"

print str1
print ''.join(reversed(str2))

def isPelindrome(str):
    strRev = ''.join(reversed(str))
    print strRev
    if strRev == str:
        return True
    else:
        return False

print isPelindrome(str1)
print isPelindrome(str2)


helleh
lufarP
helleh
True
lufarP
False


In [136]:
import string 

def isPangram(str):
    alphabate = list(string.ascii_lowercase)
    strList = list(set([l.lower() for l in str]))
    strList.sort()
    isPanGram = True
    for letter in alphabate:
        try:
            if strList.index(letter) >= 0: continue
        except ValueError:            
            isPanGram = False
            break
    print strList
    return isPanGram

str = "quick brown fox jumps over the lazy dog"

print isPangram(str)


[' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
True


In [138]:
print type(isPangram)
print type(str)
number1 = 10
print type(number1)

<type 'function'>
<type 'str'>
<type 'int'>


In [149]:
class Dog(object):
    mammel = True
    def __init__(self,breed,name,fur=True):
        self.breed = breed
        self.fur = fur
        self.name = name
        
sam = Dog(breed='puppy',name='Sammy')

print sam.mammel

True


In [47]:
class Circle(object):
    PI = 3.14
    def __init__(self,radius):
        self.radius = radius
    def area(self):
        return Circle.PI*self.radius**2
    def circumferance(self):
        return 2*Circle.PI*self.radius
    def set_radius(self,radius):
        self.radius = radius
    def get_radius(self):
        return self.radius

c1 = Circle(radius=10)
c2 = Circle(radius=20)

print c1.area()
print c2.area()
print c1.circumferance()
print c2.circumferance()
c1.set_radius(15)
print c1.area()
print c1.radius
print c2.radius

314.0
1256.0
62.8
125.6
706.5
15
20


In [155]:
GLOBAL_VARIABLES_IN_ALL_CAPS = "test"

In [157]:
l = [1,2,3,4,5]

for l1 in reversed(l):
    print l1

5
4
3
2
1


In [158]:
for i,item in enumerate(l):
    print i,item

0 1
1 2
2 3
3 4
4 5


In [161]:
l = [1,2,5,3,2,7,200,150]

for l1 in sorted(l):
    print l1
    
for l1 in sorted(l,reverse=True):
    print l1

1
2
2
3
5
7
150
200
200
150
7
5
3
2
2
1


In [166]:
class Animal(object):
    def __init__(self):
        print "Animal Created"
    def whoAmI(self):
            print "I am an Animal"
    def eat(self):
        print "eating"
        
class Dog(Animal):
    def __init__(self):
        Animal.__init__(self)
        print "Dog Created"
    def whoAmI(self):
        print "I am Dog"
    def bark(self):
        print "Woof"
        
d = Dog()
d.whoAmI()
d.eat()
d.bark()


    
        
        

Animal Created
Dog Created
I am Dog
eating
Woof


Special Methods ...cant invoke directly...python invokes based on special syntext such as len(object) print(obj)

In [173]:
class Book(object):

    def __init__(self,name,author,pages):
        self.name = name
        self.author = author
        self.pages = pages
        
    def __len__(self):
        return self.pages
            
    def __str__(self):
        return "name:%s author:%s pages:%s" %(self.name,self.author,self.pages)
    
    def __del__(self):
        print "Book deleted"
        
        
b1 = Book(name="Book1",author="Author1", pages=100)
print b1
print "Book Length: ", len(b1)

Book deleted
name:Book1 author:Author1 pages:100
Book Length:  100


Exception handling

In [174]:
try:
    2 + 's'
except:
    print 'some error occured'
else:
    print 'No exception occured'
finally:
    print 'finally block'
    

some error occured
finally block


In [175]:
try:
    2 + 2
except:
    print 'some error occured'
else:
    print 'No exception occured'
finally:
    print 'finally block'


No exception occured
finally block


In [176]:
2 + 's'

Book deleted


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [71]:
def askInt():
    while True:
        try:
            val = int(raw_input("Please enter Integer: "))
        except:
            print 'Looks like you didnt enter integer.'
#            val = int(raw_input("Try Again. Please enter Integer: "))
        else:
            print 'You entered : %d' %(val)
            break
        finally:
            print 'Finally ..'

askInt()

Please enter Integer: 1
You entered : 1
Finally ..


In [74]:
#todo
# list of common exceptions 

In [73]:
#todo
# Getting access to Exception message involves defining your own exception class

In [ ]:
#todo
# defining custom exception class and handling

In [ ]:
#todo
# loggin in python

In [2]:
import math

print math.sqrt(4)



2.0


In [3]:
from math import sqrt

print sqrt(4)

2.0


Python multiple assignments

In [4]:
a,b,c = 1,2,3
print a, b, c

1 2 3


In [5]:
import sys
sys.path.append('/Users/kavap/Documents/learn/spark/SparkCourse')

In [6]:
print sys.path

['', '/Users/kavap/anaconda/lib/python27.zip', '/Users/kavap/anaconda/lib/python2.7', '/Users/kavap/anaconda/lib/python2.7/plat-darwin', '/Users/kavap/anaconda/lib/python2.7/plat-mac', '/Users/kavap/anaconda/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/kavap/anaconda/lib/python2.7/lib-tk', '/Users/kavap/anaconda/lib/python2.7/lib-old', '/Users/kavap/anaconda/lib/python2.7/lib-dynload', '/Users/kavap/anaconda/lib/python2.7/site-packages', '/Users/kavap/anaconda/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg', '/Users/kavap/anaconda/lib/python2.7/site-packages/aeosa', '/Users/kavap/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg', '/Users/kavap/anaconda/lib/python2.7/site-packages/IPython/extensions', '/Users/kavap/.ipython', '/Users/kavap/Documents/learn/spark/SparkCourse']


In [12]:
print sys.argv[0],sys.argv[1],sys.argv[2]

 /Users/kavap/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py -f /Users/kavap/Library/Jupyter/runtime/kernel-e8b65350-a220-458b-b05c-1919ffe5cde5.json


In [13]:
__name__

'__main__'

In [ ]:
print sys.__name__

In [ ]:
from math import sqrt

math.__name__

import math

print math.sqrt(4)  # If from x import y not used, have to say x.y else can say y

Creating Modules and Packages :
 Create folder and put .py module files. The folder should have __init__.py empty file 
 Put folder in python's path
 For import a.b.c to work, folder a contains folder b contains folder c and each contains __init_.py file


In [20]:
from testpackage import module1

ImportError: No module named testpackage

In [21]:
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]

d = map(lambda x,y,z : x+y+z,a,b,c)

print d

[12, 15, 18]


In [22]:
l = [2,3,1,10,4,11,22,32,22,45,1,2]

print reduce(lambda x,y : x if x>y else y,l)

45


In [23]:
l = [2,3,1,10,4,11,22,32,22,45,1,2]

print filter(lambda x : x%2 == 0,l)

[2, 10, 4, 22, 32, 22, 2]


In [24]:
def even(x):
    if x%2 == 0:
        return True
    else:
        return False

print filter(even,l)

[2, 10, 4, 22, 32, 22, 2]


In [27]:
a = [1,2,3]
b = ['a','b','c']

print zip(a,b)

[(1, 'a'), (2, 'b'), (3, 'c')]


In [33]:
a = [1,5,9]
b = [2,3,11]

          
print map(lambda pair: max(pair), zip(a,b))          

[2, 5, 11]


### Zip uses smallest list as base

In [32]:
a = [1,2,3]
b = [4,5,6,7,8]

print zip(a,b)

[(1, 4), (2, 5), (3, 6)]


In [35]:
d1 = {'k1':'v1', 'k2':'v2'}
d2 = {'k3':'v3', 'k4':'v4'}

print zip(d1,d2)

print zip(d1,d2.itervalues())

[('k2', 'k3'), ('k1', 'k4')]
[('k2', 'v3'), ('k1', 'v4')]


In [37]:
l = ['a','b','c','d','e']
for i,item in enumerate(l):
    print i, item
    
for i,item in enumerate(l):
    if i < 3:
        print item
    else :
        print 'reached 3'
        break

0 a
1 b
2 c
3 d
4 e
a
b
c
reached 3


In [38]:
l = [True,False,False]
l1 = [True,True,True]

print all(l)
print any(l)
print all(l1)
print any(l1)

False
True
True
True


In [39]:
str = "How long are the words in this phrase"

print map(lambda x: len(x),str.split(" "))

[3, 4, 3, 3, 5, 2, 4, 6]


In [47]:
l = [3,4,3,2,1]

print reduce(lambda x,y:x*10+y,l)


34321


In [49]:
l = ['hello','are','cat','hi','dog','ham']

def filter_x(target,l):
    return filter(lambda x: x[0] == target ,l)

print filter_x('h',l)

['hello', 'hi', 'ham']


In [50]:
l1 = ['a','b','c']
l2 = ['x','y','z']
connector = '-'

def connectConcat(l1,l2,connector):
    return [pair[0] + connector + pair[1] for pair in zip(l1,l2)]

print connectConcat(l1,l2,connector)

['a-x', 'b-y', 'c-z']


In [64]:
l = ['a','b','c']

def listToDict(l):
    return {key:val for val,key in enumerate(l)}

print listToDict(l)

{'a': 0, 'c': 2, 'b': 1}


In [52]:
print dict1

[{'a': 0}, {'b': 1}, {'c': 2}]


In [58]:
l = [0,2,2,1,5,5,6,10]

print [item for i,item in enumerate(l) if i==item ]

[0, 2, 5, 6]


Variables scopr
Note how globals() and locals() can be used to debug which scope variables are referenced
Note the outputs of locals() and globals() are dictionaries
Also Note and remember some common global variables available

In [5]:
s = "Global String"


def fun1():
    print locals()
    print locals().keys()
    print globals()
    print globals().keys()
    print globals()['s']
    
fun1()   



{}
[]
{'_dh': [u'/Users/kavap/Documents/learn/python/jupyter notebooks'], '__': '', 'fun1': <function fun1 at 0x1052d4488>, '__builtin__': <module '__builtin__' (built-in)>, '_i2': u's = "Global String"\n\nprint s\n\ndef fun1():\n    print locals()\n    print locals().keys()\n    print globals()\n    print globals().keys()', 'quit': <IPython.core.autocall.ZMQExitAutocall object at 0x1041cfc10>, '_i5': u's = "Global String"\n\n\ndef fun1():\n    print locals()\n    print locals().keys()\n    print globals()\n    print globals().keys()\n    print globals()[\'s\']\n    \nfun1()    ', '_i4': u's = "Global String"\n\n\ndef fun1():\n    print locals()\n    print locals().keys()\n    print globals()\n    print globals().keys()\n    print globals()[\'s\']', '_i3': u's = "Global String"\n\nprint s\n\ndef fun1():\n    print locals()\n    print locals().keys()\n    print globals()\n    print globals().keys()\n    print globals()[\'s\']', '_iii': u's = "Global String"\n\nprint s\n\ndef fun1():\n  

## Python Decorators

Remember that Everything in Python is object. Even functions are Objects and they can be passed to other functions
Note in following example....when hello function is assigned to greet, it's by value not by reference ..so new greet function object is created from hello function object

In [63]:
def hello(name="Hello"):
    print name
    
greet = hello

greet()

del(hello)

greet()



Hello
Hello


### Returning functions
Note in following example : When you reference a function with (), it gets executed but when you reference it without (), it's being referenced. So a= hello() will execute it but a = hello assigns the function object to a.
In following example, since hello() returns another function object, a = hello() will assign, returned function object to a and make returned function code available to scope of a (which previously was unavailable)

In [17]:
def hello(name="pk",backHome=False):
    print "In hello()"
    
    def greet():
        print "Greetings %s" %(name)
    
    def welcome():
        print "Welcome back home %s" %(name)
        
    if backHome :
        return welcome
    else :
        return greet

hello()

a = hello

a()

a = hello()

a()

a = hello(backHome=True)

a()

a = hello(name="VK")

a()

a = hello(name="VK",backHome=True)

a()

In hello()
In hello()
In hello()
Greetings pk
In hello()
Welcome back home pk
In hello()
Greetings VK
In hello()
Welcome back home VK


### Functions as arguments

In following example note :
I am not passing hello() but hello since hello() willl pass return value of executing hello which is a string. Please read all comments


In [33]:
def hello():
    return "hello string"

def other(func):
    print "other function"
    print func()

other() #will return TypeError since it expects an argument of type function




TypeError: other() takes exactly 1 argument (0 given)

In [34]:
# Note that this will generate TypeError since other is expecting a function object 
# not return of executing hello() which is string

other(hello())

other function


TypeError: 'str' object is not callable

In [35]:
other(hello) 

other function
hello string


In [36]:
h = hello 
other(h)

other function
hello string


### Now the Real decorator functionality 
In following code snippet, Note :
* decorator_func needs to define a wrapper function and  execute decoratee_func passed to it as argument

In [60]:
def decorator_function(func):
    def wrapper_func():
        print "decorator code before executing decoratee code"
        func()
        print "decorator code after executing decoratee code"
    return wrapper_func
    
def decoratee_function():
    print "I am decoratee and am being decorated and here's my code"
    
decoratee_function =  decorator_function(decoratee_function)  

decoratee_function()


decorator code before executing decoratee code
I am decoratee and am being decorated and here's my code
decorator code after executing decoratee code


### @ notation for decorator

In [61]:
# Code above is better represented by Python Decorator Symbol @ as below

@decorator_function
def decoratee_function():
    print "I need a decorator"

In [55]:
decoratee_function()

code before decoratee
I need a decorator
code after decoratee


In [69]:
# Following is a practical uscase examples of decorators



In [73]:
# Trick Fibbonaci Series Q

# Wrong implementation as b is calculated as b = b + b due to a=b assignment before


def fib(n):
    a = 1
    b = 1
    for i in range(n):
        print a
        a = b
        b = a+b
        
fib(10)



1
1
2
4
8
16
32
64
128
256


In [74]:
# Trick Fibbonaci Series Q

# Correct implementation

def fib(n):
    a = 1
    b = 1
    for i in range(n):
        print a
        tmp = a
        a = b
        b = tmp+b
        
fib(10)



1
1
2
3
5
8
13
21
34
55


In [75]:
# Trick Fibbonaci Series Q

# More Pythonic implementation using multiple assignments

def fib(n):
    a = 1
    b = 1
    for i in range(n):
        print a
        a,b = b,a+b
        
fib(10)

1
1
2
3
5
8
13
21
34
55


### Generator functions

yield returns a generator(basically and iterator object) to caller and suspends till next() is called on returned object again

In [81]:
def fib(n):
    a = 1
    b = 1
    for i in range(n):
        yield a
        a,b = b,a+b
               
g = fib(3)

print g.next()
print g.next()
print g.next()
#print g.next() # This returns StopIteration exception since all iterations are done

1
1
2


StopIteration: 

In [82]:
# Same as above but better exception handling

def fib(n):
    a = 1
    b = 1
    for i in range(n):
        yield a
        a,b = b,a+b

        
g = fib(3) # g is basically an iterator object


try:
    print g.next()
    print g.next()
    print g.next()
    print g.next() # This returns StopIteration exception since all iterations are done
except : 
    print "All iterations done"
    # could also simply have pass statement

1
1
2
All iterations done


### Call to next() is implicit in for loop and for loops have builtin exception handling (I think it uses pass in except statement)     

def fib(n):
    a = 1
    b = 1
    for i in range(n):
        yield a
        a,b = b,a+b
        
for i in fib(10):
    print i

Generators are good way to : 
* Avoid save memory by avoiding pregenerating large lists and iterating over them. On the fly as needed sequences
* Dealing with infinite loops. For e.g. have generator that can generate next fibbonaci term till infinity BUT on demand so only one at a time 

In [90]:
# This function will generate Fiboonaci series for ever ..but only one at a time ...on demand
def fib():
    a = 1
    b = 1
    while True:
        yield a
        a,b = b,a+b
 
fibterm = fib()

for n in xrange(10):    # note xrange() this is another builtin generator...so we are efficient
    # print fib() is incorrect way to call and will yield wrong result
    print fibterm.next()
    
# fib() is still alive

for n in xrange(10):
    print fibterm.next()

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765


There's a differance between IterABLE and IterATOR:

a String object is iterable but not an iterator. So you can't do s.next() but you can iterate over them using for loop. 
If you need an iterator for a string, you need to pass string to an iterator function object and use that iterator object to get next() behavior

In [91]:
s = "hello"

# Can iterate over string
for l in s:
    print l

h
e
l
l
o


In [92]:
# But String itself is not iterator

s.next()

AttributeError: 'str' object has no attribute 'next'

In [97]:
# you can get an iterator if you need next() behavior
s_iterator = iter(s)

print s_iterator.next()
print s_iterator.next()
print s_iterator.next()
print s_iterator.next()
print s_iterator.next()


h
e
l
l
o


In [99]:
# Random number generator

import random

def rand_gen(n,m):
   yield random.randint(n,m)

random_number = rand_gen

for i in xrange(10):
    print random_number(1,1000).next()
    

234
746
492
324
405
93
821
555
580
604


### List Comprehension style generator function. Can be used in place of list comprehension

    doing list comprehension in () instead of [] returns generator function

In [102]:
# doing list comprehension in () instead of [] returns generator function

gen_seq = (i for item in xrange(1000) if item%2 == 0 )

for i in xrange(20):
    print gen_seq.next()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Collections module...

In [124]:
from collections import Counter

l = [1,2,2,3,1,3,2,42,4,2,4,2,1,3,1,31,3,1,3,1,3,4,4,5,6,6,1,3,22]

# Count for each unique element in list
print Counter(l) # Returns Counter object

# Can convert return value to dictionary
print dict(Counter(l))


s = "This is a very very long string which we want to count occurances of letters for we will also count number of words for and see any patterns"

# Returns Counter object
print Counter(s)

# Can convert return value to dictionary
print dict(Counter(s))

# We can also count number of words


print Counter(s.split()) # Returns Counter object

# Counter has some intersting functions too

ctr = Counter(s.split())

# Returns list of tuples
print ctr.most_common(2)

# Returns list of tuples
print ctr.items()

# Total count
print sum(ctr.values())

# List of elements
print list(ctr)





Counter({1: 7, 3: 7, 2: 5, 4: 4, 6: 2, 5: 1, 42: 1, 22: 1, 31: 1})
{1: 7, 2: 5, 3: 7, 4: 4, 5: 1, 6: 2, 42: 1, 22: 1, 31: 1}
Counter({' ': 27, 'e': 11, 'o': 11, 'n': 10, 'r': 10, 's': 9, 't': 9, 'a': 7, 'c': 6, 'w': 6, 'i': 5, 'l': 5, 'f': 4, 'u': 4, 'h': 3, 'y': 3, 'd': 2, 'g': 2, 'v': 2, 'T': 1, 'b': 1, 'm': 1, 'p': 1})
{'T': 1, 'a': 7, ' ': 27, 'c': 6, 'b': 1, 'e': 11, 'd': 2, 'g': 2, 'f': 4, 'i': 5, 'h': 3, 'm': 1, 'l': 5, 'o': 11, 'n': 10, 'p': 1, 's': 9, 'r': 10, 'u': 4, 't': 9, 'w': 6, 'v': 2, 'y': 3}
Counter({'for': 2, 'count': 2, 'we': 2, 'of': 2, 'very': 2, 'and': 1, 'letters': 1, 'is': 1, 'number': 1, 'see': 1, 'want': 1, 'any': 1, 'also': 1, 'long': 1, 'to': 1, 'which': 1, 'string': 1, 'This': 1, 'words': 1, 'a': 1, 'occurances': 1, 'will': 1, 'patterns': 1})
[('for', 2), ('count', 2)]
[('and', 1), ('letters', 1), ('is', 1), ('number', 1), ('see', 1), ('want', 1), ('any', 1), ('for', 2), ('also', 1), ('long', 1), ('to', 1), ('which', 1), ('count', 2), ('we', 2), ('string', 

### Datetime

In [148]:
import datetime

print datetime.date.today()

#Create a time object
t1 = datetime.time(1,2,3,00001)
print t1

d1 = datetime.date(2016,12,31)
print d1

d2 = datetime.date.today()
print d2

print d2-d1

print datetime.time.resolution

print datetime.date.resolution

t = datetime.time(4, 20, 1, 001010)

# Lets show the different components

print t
print 'hour  :', t.hour
print 'minute:', t.minute
print 'second:', t.second
print 'microsecond:', t.microsecond
print 'tzinfo:', t.tzinfo

today = datetime.date.today()
print today
print 'ctime:', today.ctime()
print 'tuple:', today.timetuple()
print 'ordinal:', today.toordinal()
print 'Year:', today.year
print 'Mon :', today.month
print 'Day :', today.day


print 'Earliest  :', datetime.time.min
print 'Latest    :', datetime.time.max
print 'Resolution:', datetime.time.resolution

print 'Earliest  :', datetime.date.min
print 'Latest    :', datetime.date.max
print 'Resolution:', datetime.date.resolution


# Can change just part of day and clone
d1 = datetime.date(2015, 3, 11)
print 'd1:', d1

d2 = d1.replace(year=1990)
print 'd2:', d2

2017-01-27
01:02:03.000001
2016-12-31
2017-01-27
27 days, 0:00:00
0:00:00.000001
1 day, 0:00:00
04:20:01.000520
hour  : 4
minute: 20
second: 1
microsecond: 520
tzinfo: None
2017-01-27
ctime: Fri Jan 27 00:00:00 2017
tuple: time.struct_time(tm_year=2017, tm_mon=1, tm_mday=27, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=4, tm_yday=27, tm_isdst=-1)
ordinal: 736356
Year: 2017
Mon : 1
Day : 27
Earliest  : 00:00:00
Latest    : 23:59:59.999999
Resolution: 0:00:00.000001
Earliest  : 0001-01-01
Latest    : 9999-12-31
Resolution: 1 day, 0:00:00
d1: 2015-03-11
d2: 1990-03-11


### Python debugger

* When you see an error at line n, goto a line before that and say pdb.set_trace()
* On interactive console, inquire about various variable values
* Can also perform variable expressions such as x+y and see errors thrown and then inquire things such as if variables types mismatch, etc
* Type quit to get out of debugger
* Good debuggin advice : https://docs.python.org/2/library/pdb.html

In [149]:
import pdb

x = [1,2,3]
y = 2
z = 3

print y+z

# Error will say error at line 9 etc 
print x+y


5


TypeError: can only concatenate list (not "int") to list

In [151]:
import pdb

x = [1,2,3]
y = 2
z = 3

print y+z

pdb.set_trace()
# Error will say error at line 9 etc 
print x+y


5
--Return--
> <ipython-input-151-d87ad2b2c262>(9)<module>()->None
-> pdb.set_trace()
(Pdb) x
[1, 2, 3]
(Pdb) y
2
(Pdb) z
3
(Pdb) y+z
5
(Pdb) x+y
*** TypeError: can only concatenate list (not "int") to list
(Pdb) quit


BdbQuit: 

#### Time estimates for run time can be done two ways :
* Python's timeit library
* Jupyter's magic %timeit 

In [155]:
import timeit

# For loop
timeit.timeit('"-".join(str(n) for n in range(100))', number=10000)

0.8997578620910645

In [156]:
# List comprehension
timeit.timeit('"-".join([str(n) for n in range(100)])',number=10000)

0.5597290992736816

In [161]:
# Map()
timeit.timeit('"-".join(map(str,range(100)))',number=10000)

0.21224594116210938

#### We can also use Jupyter magic function %timeit
     Note : No need to embed expression in '' and specify # of loops ...Jupyter determines and manages it

In [162]:
%timeit "-".join(str(n) for n in range(100))

10000 loops, best of 3: 38.3 µs per loop


### Regular expressions

#### Repeatations :

'sd*',     # s followed by zero or more d's

'sd+',     # s followed by one or more d's

'sd?',     # s followed by zero or one d's

'sd{3}',   # s followed by three d's

'sd{2,3}', # s followed by two to three d's

'[sd]',    # either s or d

's[sd]+']  # s followed by one or more s or d

'[a-z]+',  # sequences of lower case letters

'[A-Z]+',   # sequences of upper case letters

'[a-zA-Z]+', # sequences of lower or upper case letters

'[A-Z][a-z]+']  # one upper case letter followed by lower case letters

#### Negative patterns

's[^aeiou]' # s NOT followed by a/e/i/o/u

#### Escape characters

\d	a digit

\D	a non-digit

\s	whitespace (tab, space, newline, etc.)

\S	non-whitespace

\w	alphanumeric

\W	non-alphanumeric


##### Note r in front of patterns. This is to avoid conflict with python's internal patterns

test_patterns=[ r'\d+', # sequence of digits
                r'\D+', # sequence of non-digits
                r'\s+', # sequence of whitespace
                r'\S+', # sequence of non-whitespace
                r'\w+', # alphanumeric characters
                r'\W+', # non-alphanumeric
                ]
                
                





In [31]:
import re

pattern = "\d+/\d+/\d+"

text = "vihaan was born on 9/23/12 where as vijal was born on 09/15/1979"

match = re.search(pattern,text)

print type(match)

print match.start(),match.end()

print re.findall(pattern,text) #Returns a list

# If asked to find domain name in emails

email = "kavap@hotmail.com"  # Returns a list

print re.split('@',email)

#Split based on space or punctuations
test_phrase = 'This is a string! But it has punctuation. How can we remove it?'

re.findall('[^!.? ]+',test_phrase)



<type '_sre.SRE_Match'>
19 26
['9/23/12', '09/15/1979']
['kavap', 'hotmail.com']


['This',
 'is',
 'a',
 'string',
 'But',
 'it',
 'has',
 'punctuation',
 'How',
 'can',
 'we',
 'remove',
 'it']

### Advanced sets

In [32]:
s = set()

In [49]:
s.add(1)
s.add(2)
s.add(3)

s

s.add(555)

s

s.discard(555)
s

s.clear()

s

s.add(1)
s.add(2)
s.add(3)

s

sc = s.copy()

sc

s.add(4)

s

s.difference(sc)

s1 = {1,2,3,4}

s2 = {1,2,3}

s1.intersection(s2)

s1 = {1,2}
s2 = {1,2,4}
s3 = {5}

print s1.isdisjoint(s3)
print s1.isdisjoint(s2)

print s1.issubset(s2)

print s2.issuperset(s1)

s1.symmetric_difference(s2)

s1.union(s2) #Unioned set has all unique elements from both sets



True
False
True
True


{1, 2, 4}

### Testing Code


In [67]:
# todo

### Common functions

### Case for  using functions

* When possible use Python built in functions. Why ? They are all written using C..so they are inherently faster

In [70]:
s = "Mixed Case String"

print s.lower()
print s.upper()



mixed case string
MIXED CASE STRING


## NumPy, Pandas, Scikit-learn, Beautifulsoup

#### numpy
* Linear Algebra Lib
* Many other libraries (pandas, scikit-learn, etc) built on top of numpy
* Very fast as many of the functions in numpy are bound to compiled C code based functions  
* Try using Ananconda distribution to get numpy and other dependencies 
    * conda instal numpy
* numpy arrays 
    * Each element must be of same data type
    * vectors - 1d
    * matrices - 2d
    * Terminology
        * Dimensions of an array is called shape of an array
        * numpy has functions to "reshape" array
#### Prefer Universal functions where available as they are space and time efficient

In [6]:
# Convert list of list of lists into numpy array tp be able to use numpy functions

import numpy as np

l1 = [1,2,3]
l2 = [[1,2,3],[4,5,6],[7,8,9]]

a1 = np.array(l1)
a2 = np.array(l2)

print a1
print a2

a1

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3])

In [12]:
# numpy has its own range function called arange

import numpy as np

a1 = np.arange(0,11,2)

print a1

a2 = np.zeros(10)

print a2

# Notice two sets of braces..shape is passed as Tuple here
a3 = np.zeros((3,3))

print a3

print np.ones(3)




[ 0  2  4  6  8 10]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[ 1.  1.  1.]


In [13]:
# 10 evenly spaced points

import numpy as np

# 1d vector
a1 = np.linspace(0,1,10)

print a1

# 2d vector
a2 = np.linspace(0,1,)

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]


In [14]:
# Identity matrix - Symmetric metrix with 1s in major diagonal and rest 0s

import numpy as np

e1 = np.eye(4)

print e1


[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [20]:
# Generating vectors and metrices of Random numbrs from different distributions

# Checkout all different random functions available by np.random.<Tab>

import numpy as np

r1 = np.random.rand(5)  # random numbers from standard uniform distribution. No -ve numbers

r2 = np.random.rand(3,3)  # Note here we are not passing Tuple..directly two parameters

print r1
print r2

r1 = np.random.randn(5) # random numbers from Gaussian distribution. Standard dist. centered 
print r1                # around zero. Can have -ve numbers

print np.random.randn(2,2)

r3 = np.random.randint(1,100)  # 100 not included. So 0 probability of included. Returns single
print r3                       # integer

r4 = np.random.randint(1,100,5) # Array of 5 integers. 100 not inclusive
print r4

[ 0.76134686  0.87043463  0.46874441  0.85980458  0.22896912]
[[ 0.76844177  0.37085856  0.03877433]
 [ 0.90359111  0.99843017  0.11785292]
 [ 0.87181681  0.49210023  0.67019924]]
[ 0.49975756  0.49152562  0.2653217  -0.56896784 -0.62760012]
[[ 0.77074184  0.14738216]
 [-0.62765198  1.12119275]]
39
[41 21 38 45 80]


In [51]:
# Array Reshaping
# Reshaped array must contain same number of elements as original
# Reshape can be used to serialize and deserialize

import numpy as np

a1 = np.random.randint(1,50,10)

print a1

a2 = a1.reshape(5,2) #Note Reshaped Array must contain same number of elements

print a2 

a3 = a2.reshape(10)

print a3

# Find shape of given array. Note shape is not a method, it's a variable
# Note the returned value is always Tuple

print a1.shape
print a2.shape

# Another example of reshape

a1 = np.arange(50).reshape(5,10)

print a1


[21 18  9  8 13 36 30 47  5 36]
[[21 18]
 [ 9  8]
 [13 36]
 [30 47]
 [ 5 36]]
[21 18  9  8 13 36 30 47  5 36]
(10,)
(5, 2)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [23]:
# max, min and index

import numpy as np

a1 = np.random.randint(1,50,20)

print a1

print a1.max(), a1.min(), a1.argmax(),a1.argmin()

[23 42 16 21 22 16  3 12 42 27 24 11 30 37 44 15 18 17  9 49]
49 3 19 6


In [ ]:
# Array Indexing and Slicing

In [43]:
import numpy as np

a1 = np.random.randint(1,50,20)

print a1

print a1[4]

print a1[0:5]  # Grab 0 upto index 5 but not 5. Note that 5 is not included in returned slice

print a1[:5] # Grab 0 upto index 5 but not 5. Note that 5 is not included in returned slice

print a1[5:] # Grab from index 5 including 5. Note that index 5 is included in returned slice

print a1[:] # Grab everything


# Note slicing returns views on Arrays and not a  new Array

a2 = a1[0:5]

print a1
print a2

# If we need a copy of array and not reference

a3 = a1.copy()

a3[:] = 100

print a3
print a1

a2[:] = 100 # Note it's a2[:] = 100 and not a2 = 100

print a2
print a1


# Note it's a2[:] = 100 and not a2 = 100
a2 = 100

print a2







[26 34  1 36 46 17 31 48 16 33 19  4  2 36 28  7 24 40  6 49]
46
[26 34  1 36 46]
[26 34  1 36 46]
[17 31 48 16 33 19  4  2 36 28  7 24 40  6 49]
[26 34  1 36 46 17 31 48 16 33 19  4  2 36 28  7 24 40  6 49]
[26 34  1 36 46 17 31 48 16 33 19  4  2 36 28  7 24 40  6 49]
[26 34  1 36 46]
[100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100]
[26 34  1 36 46 17 31 48 16 33 19  4  2 36 28  7 24 40  6 49]
[100 100 100 100 100]
[100 100 100 100 100  17  31  48  16  33  19   4   2  36  28   7  24  40
   6  49]
100


In [46]:
# Indexing and Grabing slices of matrices

import numpy as np

a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])


print a1
print a1[1,1]  # This and following notation are same
print a1[1][1]
print a1[:2,1:] # Grab upto row at index 2 but not 2 and from column at index 1 including 1



[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
5
[[2 3]
 [5 6]]


In [41]:
# Arrays have Broadcast capabilities, Lists don't

import numpy as np

l1 = [1,2,3]

a1 = np.arange(3)

print l1
print a1


# Following broadcasts operation to each numpy Array element
a1 += 5

print a1

print a1*5



# Following operation on list is different from Array...following expands list by making 5 copies of elements  
l1 = l1 * 5
print l1

# Can't do following. Results in TypeError exception
l1 = l1 + 5
print l1





[1, 2, 3]
[0 1 2]
[5 6 7]
[25 30 35]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [50]:
# Conditional selection in Array

import numpy as np

a1 = np.random.randint(1,50,20)

print a1

a1_boolean = a1 > 5

print a1_boolean

a2 = a1[a1_boolean]

print a2

# Above two steps are same as 

a2 = a1[a1>5]  # [expression that returns boolean]

print a2

[49 44 48 40 41 27  6 23 22 49 11 28  4 27 14 21  1 30 18 46]
[ True  True  True  True  True  True  True  True  True  True  True  True
 False  True  True  True False  True  True  True]
[49 44 48 40 41 27  6 23 22 49 11 28 27 14 21 30 18 46]
[49 44 48 40 41 27  6 23 22 49 11 28 27 14 21 30 18 46]


#### Array Operations
     - Array and Scalars (aka Matrix and Scalars)
     - Arrays and Arrays 
     - Universal Array functions
#### Prefer Universal functions where available as they are space and time efficient     

In [69]:
import numpy as np

# Array Ops with other Array

print "Array Ops with other Array"

a1 = np.arange(10)
print a1

a2 = a1 + a1
print a2

a2 = a1*a1
print a2

# Array Ops with Scalar

print "Array Ops with Scalar"

a2 = a1+5
print a2

a2 = a1*5
print a2

a2 = a1 ** 2 # Exponents
print a2


# Note that numpy Array Ops return nan in result and  a Warning in cases such as 0/0 or 
# return inf in n/0 where n!=0. numpy array doesn't return exception as non numpy objects do

print "Exception and Warnings"
a2 = a1/a1

print a2

a2 = a1/0

print a2

# print 1/0 # This results in exception


# Universal functions applies to each array element
# do np.<tab> to see what functions are available

print "Universal functions applies to each array element"

print np.sqrt(a1)
print np.cbrt(a1) # Cube root
print np.square(a1)
print np.reciprocal(a1) # 1/x where x is each element

print np.exp(a1) # base e
print np.exp2(a1) # base 2
print np.expm1(a1) # Calculate exp(x) - 1 for all elements in the array.

print np.log(a1) # log base e
print np.log2(a1) # log base 2
print np.log10(a1) # log base 10
print np.log1p(a1) # Return the natural logarithm of one plus the input array, element-wise.


print np.min(a1), np.max(a1)
print np.negative(a1)
print np.absolute(a1)
print np.sin(a1)
print np.log(a1)  # log(0) = inf
print np.add(a1,a1)  #suntract/multiply/divide/true_divide/floor_divide/power/remainder/mod/
                     # 

# Before building any Array ops function, check if one is available at :
# https://docs.scipy.org/doc/numpy/reference/ufuncs.html




Array Ops with other Array
[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
Array Ops with Scalar
[ 5  6  7  8  9 10 11 12 13 14]
[ 0  5 10 15 20 25 30 35 40 45]
[ 0  1  4  9 16 25 36 49 64 81]
Exception and Warnings
[0 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
Universal functions applies to each array element
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
[ 0  1  4  9 16 25 36 49 64 81]
[-9223372036854775808                    1                    0
                    0                    0                    0
                    0                    0                    0
                    0]
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03]
[   1.    2.    4.    8.   16.   32.   64.  128.  256.  512.]
[  0.00000000e+00   1.71828183e+00   6.3890561

/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:34: RuntimeWarning: divide by zero encountered in divide
/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:38: RuntimeWarning: divide by zero encountered in divide
/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:52: RuntimeWarning: divide by zero encountered in reciprocal
/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:52: RuntimeWarning: invalid value encountered in reciprocal
/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:58: RuntimeWarning: divide by zero encountered in log
/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipykernel/__main__.py:59: RuntimeWarning: divide by zero encountered in log2
/Users/kavap/Library/Enthought/Canopy_64bit/User/lib/python2.7

## pandas
* pandas is built on numpy (so eventually on functions implemented in C) and is fast
* Data ingestion, cleaning, preparation, transformation and visualization

#### Series

In [82]:
import numpy as np
import pandas as pd

my_data = [1,2,3]
my_labels = ['a','b','c']
numpy_array = np.arange(3)
d_dict = {'a':1,'b':2,'c':3}

# Different ways to construct pandas series

s1 = pd.Series(data=my_data) # Default labels are index values
print s1

s1 = pd.Series(data=my_data,index=my_labels) #note S is uppercase in Series
print s1

s1 = pd.Series(my_data,my_labels) # as long as data and index are passed in that order
print s1

s1 = pd.Series(numpy_array,my_labels)
print s1

s1 = pd.Series(d_dict)  # If object type of first parameter is dictionary, the lables are taken
                        # from dictionary indexes
print s1

# Series operations

s1 = pd.Series([1,2,3,11],['USA','Germany','Japan','Italy'])
print s1

s2 = pd.Series([4,5,6,7,8],['USA','India','Germany','Australia','Japan'])
print s2

print s1+s2 # Perform operation on Series elements where labels match. Where lables dont match,
            # output contains label with value NaN




0    1
1    2
2    3
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
dtype: int64
a    0
b    1
c    2
dtype: int64
a    1
b    2
c    3
dtype: int64
USA         1
Germany     2
Japan       3
Italy      11
dtype: int64
USA          4
India        5
Germany      6
Australia    7
Japan        8
dtype: int64
Australia     NaN
Germany       8.0
India         NaN
Italy         NaN
Japan        11.0
USA           5.0
dtype: float64


#### Dataframes
* Dataframe is a number of series put together so that they share index
* Dataframe is basically a  numpy 2d matrix with labels for both dimensions
* 

In [106]:
import numpy as np
import pandas as pd
from numpy.random import randn 

np.random.seed(101) #Seeds random number generator to generate psudo random # seeded by 101

data_matrix = randn(5,4)
print data_matrix

df1 = pd.DataFrame(data=data_matrix,index='A B C D E'.split(),columns='X Y Z W'.split())

print df1
print type(df1) # Note df1 is object of type DataFrame

print df1['W']
print type(df1['W']) # Note a column is dataframe is basically a series

print df1[['W','X']]
print type(df1[['W','X']]) #Selecting multiple columns from a dataframe creates  a dataframe


# Creating new columns using dataframe operations

df1['new'] = df1['W'] + df1['X']

print df1

# Creating new Dataframe with 1 less column

df2 = df1.drop('W',axis=1)   # Note that column axis needs to be specified 
print df2
print df1 # Note that original dataframe still has 'W'

df1.drop('W',axis=1,inplace=True)  #To remove a column from a Dataframe, inplace has to set to True
print df1

# Both row and columns can be dropped
df2.drop('A',inplace=True) # Note Axis not specified as default axis is 0 (row)
print df2 


# Selecting a column or set of columns
df1 = pd.DataFrame(data=data_matrix,index='A B C D E'.split(),columns='X Y Z W'.split())

print df1['W']
print df1[['W','Z']] #Note double [[]] we need to provide list of columns in []


# Selecting row(s) needs special functions

print df1.loc['A']   #note wierd function bracket here [] instead of ()
print type(df1.loc['A'])  #Note that even a single row is a series 

print df1.loc[['A','C']]
print type(df1.loc[['A','C']]) #Multiple rows on other hand is a dataframe

print df1.iloc[1] #in looping scenarios, we can use index of row as well


# Selecting subset of rows and columns
print df1.loc['B','X'] #Note here, the row and column labels are not given in list. If it was list it would be treated as list of rows

print df1.loc[['A','B'],['X','Y']]  #The elements can be from contiguous rows and columns or 
print df1.loc[['A','C'],['X','Z']] # from non contiguous rows and non contiguous columns





[[ 2.70684984  0.62813271  0.90796945  0.50382575]
 [ 0.65111795 -0.31931804 -0.84807698  0.60596535]
 [-2.01816824  0.74012206  0.52881349 -0.58900053]
 [ 0.18869531 -0.75887206 -0.93323722  0.95505651]
 [ 0.19079432  1.97875732  2.60596728  0.68350889]]
          X         Y         Z         W
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509
<class 'pandas.core.frame.DataFrame'>
A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: W, dtype: float64
<class 'pandas.core.series.Series'>
          W         X
A  0.503826  2.706850
B  0.605965  0.651118
C -0.589001 -2.018168
D  0.955057  0.188695
E  0.683509  0.190794
<class 'pandas.core.frame.DataFrame'>
          X         Y         Z         W       new
A  2.706850  0.628133  0.907969  0.503826  3.210676
B  0.651118 -0.319318 -0.848077  0.605965  1.25708

In [117]:
# Conditional selection

import numpy as np
import pandas as pd
from numpy.random import randn 

np.random.seed(101) #Seeds random number generator to generate psudo random # seeded by 101

data_matrix = randn(5,4)
print data_matrix

df1 = pd.DataFrame(data=data_matrix,index='A B C D E'.split(),columns='X Y Z W'.split())

# Conditional selection

bool_df1 = df1 > 0
print bool_df1

print df1[bool_df1] #Rarely used op. But note it applies the condition on each element. 
                    # output here contains result of applying condition to each element
                    # Note NaN in places where condition is false

# Above can be written in one line
print df1[df1>0]

# More common usage though is like filtering based on column or row values 
# In those cases, unlike above, only matching rows/columns are returned in output DataFrame
# Similar to excel custom filters

print df1[df1['W'] > 0] #Return only those rows  where column W value > 0. All columns are returned

# We can trim down which columns are included in result

print df1[df1['W'] > 0 ] [['Y','X']] # Note since returned value is DataFrame, we can perform
                                   # DataFrame specific operation. Note [[]] to supply list of columns

# We can provide multple conditions
# Note we use & as well as | as opposed to Python's normal and / or  operators
# Also note that each term in expression is in ()

print df1[(df1['W'] > 0) & (df1['Y'] > 1)]

print df1[(df1['W'] > 0) | (df1['Y'] > 1)]



[[ 2.70684984  0.62813271  0.90796945  0.50382575]
 [ 0.65111795 -0.31931804 -0.84807698  0.60596535]
 [-2.01816824  0.74012206  0.52881349 -0.58900053]
 [ 0.18869531 -0.75887206 -0.93323722  0.95505651]
 [ 0.19079432  1.97875732  2.60596728  0.68350889]]
       X      Y      Z      W
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True
          X         Y         Z         W
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509
          X         Y         Z         W
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509
          X         Y         Z         W
A  2.706850  0.628

In [124]:
# Resetting and Changing Index

# Reset index makes orginal index as a column and sets numerical index as index
print df1.reset_index() #Note to permantently reset index, reset_index(inplace=True)



states = "NY CA MA NV NJ".split()
print states
df1['States'] = states
print df1

# To set index to values in any column

print df1.set_index('States') # This overwrites existing index and we loose original index
print df1                     # Note to do perm index set, inplace=True needed



  index         X         Y         Z         W States
0     A  2.706850  0.628133  0.907969  0.503826     NY
1     B  0.651118 -0.319318 -0.848077  0.605965     CA
2     C -2.018168  0.740122  0.528813 -0.589001     MA
3     D  0.188695 -0.758872 -0.933237  0.955057     NV
4     E  0.190794  1.978757  2.605967  0.683509     NJ
['NY', 'CA', 'MA', 'NV', 'NJ']
          X         Y         Z         W States
A  2.706850  0.628133  0.907969  0.503826     NY
B  0.651118 -0.319318 -0.848077  0.605965     CA
C -2.018168  0.740122  0.528813 -0.589001     MA
D  0.188695 -0.758872 -0.933237  0.955057     NV
E  0.190794  1.978757  2.605967  0.683509     NJ
               X         Y         Z         W
States                                        
NY      2.706850  0.628133  0.907969  0.503826
CA      0.651118 -0.319318 -0.848077  0.605965
MA     -2.018168  0.740122  0.528813 -0.589001
NV      0.188695 -0.758872 -0.933237  0.955057
NJ      0.190794  1.978757  2.605967  0.683509
          X     

In [138]:
# Multi level index

import numpy as np
import pandas as pd
from numpy.random import randn

outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]

hier_index_tuples = list(zip(outside,inside))
print hier_index_tuples

hier_index = pd.MultiIndex.from_tuples(hier_index_tuples)
print hier_index  # We are creating multi-level row labeling scheme

df1 = pd.DataFrame(randn(6,2),index=hier_index,columns=['A','B']) 

print df1  

#Notice except for deepest level of hierarchy, each level is composed of sub dataframes
# Indexing based access

print df1.loc['G1']

print df1.loc['G1'].loc[1]

print df1.loc['G1'].loc[1]['A']

# Each level can be assigned a name
print df1.index.names # By default the name of each level is None

df1.index.names = ["Group","Num"]  # Number of elements in list = Number of levels

print df1.index.names

print df1

# Now we can use Cross section function to nagigate and do advanced selection of rows 

print df1.xs('G1') # All rows in G1
print df1.xs(['G1',1]) # All rows in G1.1

# Advanced selection using cross section function

print df1.xs(1,level="Num")  # All rows where index = 1 in "Num" level of index hierarchy


[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]
MultiIndex(levels=[[u'G1', u'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])
             A         B
G1 1  0.975720 -0.388239
   2  0.783316 -0.708954
   3  0.586847 -1.621348
G2 1  0.677535  0.026105
   2 -1.678284  0.333973
   3 -0.532471  2.117727
          A         B
1  0.975720 -0.388239
2  0.783316 -0.708954
3  0.586847 -1.621348
A    0.975720
B   -0.388239
Name: 1, dtype: float64
0.975719680344
[None, None]
[u'Group', u'Num']
                  A         B
Group Num                    
G1    1    0.975720 -0.388239
      2    0.783316 -0.708954
      3    0.586847 -1.621348
G2    1    0.677535  0.026105
      2   -1.678284  0.333973
      3   -0.532471  2.117727
            A         B
Num                    
1    0.975720 -0.388239
2    0.783316 -0.708954
3    0.586847 -1.621348
A    0.975720
B   -0.388239
Name: (G1, 1), dtype: float64
              A         B
Group               

In [8]:
# How to deal with missing values

import numpy as np
import pandas as pd

df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

print df

## Dropping rows/columns with missing values

# Drop all rows with even 1 missing value. Note we are not performing inplace operation

print df.dropna()  # By default axis = 0

# Drop all columns with even 1 missing value. Note we are not performing inplace operation

print df.dropna(axis=1)

print df

# Drop rows with fewer than 'thresh' valid values.Note we are not performing inplace operation
print df.dropna(thresh=2)

## Flling in values where missing
# Several fill functions can be used. Choose ones appropriate for situation and dataset
# For e.g. filling with column average maintains the average across dataset

print df['A'].fillna(value=df['A'].mean())


     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3
     A    B  C
0  1.0  5.0  1
   C
0  1
1  2
2  3
     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3
     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
0    1.0
1    2.0
2    1.5
Name: A, dtype: float64


In [16]:
#groupby

import numpy as np
import pandas as pd

data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350],'Profits':[100,60,170,62,121,175]}

df = pd.DataFrame(data)

print df

df.groupby('Company')  # Creates an object of type DataFrameGroupBy which has various aggregation
                       # methods
    
print df.groupby('Company').count() #Group by company and show count of each company


print df.groupby('Company').min()  # Note the min() function applies to all numeric columns and 
print df.groupby('Company').max()  # Doesnt apply to any String column
print df.groupby('Company').mean()
print df.groupby('Company').describe() #Provides common statistical aggregations for each grouping key
print df.groupby('Company').describe().transpose() # Statistics in horizontal format
print df.groupby('Company').describe().transpose()['GOOG']




  Company   Person  Profits  Sales
0    GOOG      Sam      100    200
1    GOOG  Charlie       60    120
2    MSFT      Amy      170    340
3    MSFT  Vanessa       62    124
4      FB     Carl      121    243
5      FB    Sarah      175    350
         Person  Profits  Sales
Company                        
FB            2        2      2
GOOG          2        2      2
MSFT          2        2      2
          Person  Profits  Sales
Company                         
FB          Carl      121    243
GOOG     Charlie       60    120
MSFT         Amy       62    124
          Person  Profits  Sales
Company                         
FB         Sarah      175    350
GOOG         Sam      100    200
MSFT     Vanessa      170    340
         Profits  Sales
Company                
FB         148.0  296.5
GOOG        80.0  160.0
MSFT       116.0  232.0
                  Profits       Sales
Company                              
FB      count    2.000000    2.000000
        mean   148.000000  296.

In [34]:
# Concatenation, Merge, Joins
# Note that result is a dataframe

import pandas as pd

df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

print "df1 \n",df1
print "df2 \n",df2
print "df3 \n",df3

# When Concatenating, concatenate along the Axis where dimensions match
# Note concat is a universal function

print "Concatenating"
print pd.concat([df1,df2,df3]) #Concat along default axis 0..rows
                                # Note concat accepts a List of dataframes in []
print pd.concat([df1,df2,df3],axis=1) #Notice missing values in results as dimensions dont match along axis 1


# Merging - Combine based on matching column keys
# Note Merge, Concat and Join are pandas universal functions. So pd.merge
# Remember diff between merge and join
#    - merge is based on matching key columns. join is based on matching index values (rows)
#    - merge is universal function (pd.merge). join is method of dataframe object (df.join) 
#    - Both merge and join results have all columns from both left and right dataframes

# Notice 'key' column. merging and joining is done based on keys
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']}) 

print "Merging"
print "left \n",left
print "right \n",right

print pd.merge(left,right,how='inner',on='key') #Join columns from both sides and keep 
                                                # rows only where keys match
    

left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

print "left \n", left
print "right \n", right
# Note that by default how='inner'
print pd.merge(left,right,on=['key1','key2']) #Note keys in []. Also, this represents composite
                                              # key merge


# how = 'outer' -- matching rows + non matching from left + non matching from right. All col from left and right
print "Outer composite key"
print pd.merge(left,right,how='outer',on=['key1','key2'])

# how = 'left' -- matching rows + non matching from left . All col from left and right
print "Left composite key"
print pd.merge(left,right,how='left',on=['key1','key2'])

# how = 'right' -- matching rows + non matching from right. All col from left and right
print "Right composite key"
print pd.merge(left,right,how='right',on=['key1','key2'])
    

# Joining
# Remember diff between merge and join
#    - merge is based on matching key columns. join is based on matching index values (rows)
#    - merge is universal function (pd.merge). join is method of dataframe object (df.join) 
#    - Both merge and join results have all columns from both left and right dataframes


left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

print "\n\n Joining \n\n"
print "\n left \n\n",left
print "\n right \n\n",right

print "\n\n Inner Join \n\n"
print left.join(right)  # Keep rows where indexes match + rows from left where indexes don't match. 
                        # combine columns from left and right

# keep rows where indexes match + rows from left and right where indexes don't match
print "\n\n Outer Join  \n\n"
print left.join(right,how='outer')  

    



df1 
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
df2 
    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
df3 
      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
Concatenating
      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN

In [54]:
# DataFrame Operations

import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

# first few rows
print df.head()
print df.head(2)

print df['col2'].unique()

print df['col2'].nunique() #distinct count

print df['col2'].value_counts() # Count by each unique value

# selecting data

print df[(df['col1'] > 2) & (df['col2'] == 444 )]

# Applying a function to a column

def times2(x):
    return x*2

print df['col1'].apply(times2)        # Note the returned object is a series corresponding to 
print type(df['col1'].apply(times2))  # resulting column

print df['col3'].apply(len) # apply can take standard or library function as well as custom

print df['col1'].sum() #Note the method is called on Series object and returns a scalar


# Remove column

del df['col1']

print df

df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})

print df.columns
print df.index

print df.sort_values(by='col2') #inplace=False by default

print df.isnull() #returns boolean DataFrame with True/False for each element


# Pivot table

data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

print " \n Pivot table : \n"
print "\n DataFrame : \n",df


## Note : index specifies rows hierarchy. Each value in 'columns' column becomes a new column
## Notice NaN values in cells where there are no rows in DataFrame for rows and column intersections
print " \n Pivot table : \n"
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])




   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz
   col1  col2 col3
0     1   444  abc
1     2   555  def
[444 555 666]
3
444    2
555    1
666    1
Name: col2, dtype: int64
   col1  col2 col3
3     4   444  xyz
0    2
1    4
2    6
3    8
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>
0    3
1    3
2    3
3    3
Name: col3, dtype: int64
10
   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz
Index([u'col1', u'col2', u'col3'], dtype='object')
RangeIndex(start=0, stop=4, step=1)
   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi
    col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
 
 Pivot table : 


 DataFrame : 
     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1
 
 Pivot table : 



C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [9]:
# pandas input and output

import pandas as pd

# csv
df = pd.read_csv("/Users/kavap/Documents/learn/python/jupyter notebooks/Python-Data-Science-and-Machine-Learning-Bootcamp/Python-for-Data-Analysis/Pandas/example")
print df

# write to csv
df.to_csv("/Users/kavap/Downloads/example-test-pk",index=False) #index --header

df1 = pd.read_csv("/Users/kavap/Downloads/example-test-pk")

print df1


# excel
# keep in mind, this only imports data. Not formulas or images, 
# having images or macros may cause this read_excel method to crash.
# Requires "openpyxl" dependency installed 

# Each sheet is a DataFrame. Use one statement for each sheet
df = pd.read_excel('/Users/kavap/Downloads/Excel_Sample.xlsx',sheetname='Sheet1') 

print df


# html
# Needs dependencies : lxml, html5lib, BeautifulSoup4
# From target html, extracts each table and creates a list of DataFrames
# Note that Beautifulsoup4 can provide very advanced webscrapping capabilities

df_list = pd.read_html("http://www.fdic.gov/bank/individual/failed/banklist.html")

print df_list[0].info() # prints info about DataFrame.columns..indexes..count..etc
print df_list[0].head(10)



# Notice while writing it's sheet_name and while reading it's sheetname
df.to_excel('/Users/kavap/Downloads/Excel_Sample-test-pk.xlsx',sheet_name='Sheet1')

df1 = pd.read_excel('/Users/kavap/Downloads/Excel_Sample-test-pk.xlsx',sheetname='Sheet1')


    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
Bank Name                550 non-null object
City                     550 non-null object
ST                       550 non-null object
CERT                     550 non-null int64
Acquiring Institution    550 non-null object
Closing Date             550 non-null object
Updated Date             550 non-null object
dtypes: int64(1), object(6)
memory usage: 30.1+ KB
None
                       Bank Name                City  ST   CERT  \
0                  Proficio Bank  Cottonwood Heights  UT  35495   
1  Seaway Bank and Trust Company             Chicago  IL  19328   
2         Harvest Community Bank          Pennsville  N

ImportError: No module named openpyxl

#### SQL input and output from pandas 

* The pandas.io.sql module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API. 
* Database abstraction is provided by SQLAlchemy if installed. 
* In addition you will need a driver library for your database. Examples of such drivers are psycopg2 for PostgreSQL or pymysql for MySQL. 
* For SQLite this is included in Python’s standard library by default. You can find an overview of supported drivers for each SQL dialect in the SQLAlchemy docs.
* If SQLAlchemy is not installed, a fallback is only provided for sqlite (and for mysql for backwards compatibility, but this is deprecated and will be removed in a future version). This mode requires a Python database adapter which respect the Python DB-API.

See also some cookbook examples for some advanced strategies.

The key functions are:

* read_sql_table(table_name, con[, schema, ...])	
    * Read SQL database table into a DataFrame.
* read_sql_query(sql, con[, index_col, ...])	
    * Read SQL query into a DataFrame.
* read_sql(sql, con[, index_col, ...])	
    * Read SQL query or database table into a DataFrame.
* DataFrame.to_sql(name, con[, flavor, ...])	
    * Write records stored in a DataFrame to a SQL database.

In [ ]:
# pandas input and output - SQL
# todo
